"""init

Revision ID: 76c55e9571a3
Revises: 
Create Date: 2026-07-10 18:57:23.788745

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '76c55e9571a3'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('images',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('filename', sa.String(length=255), nullable=False),
    sa.Column('width', sa.Integer(), nullable=False),
    sa.Column('height', sa.Integer(), nullable=False),
    sa.Column('file_size', sa.Integer(), nullable=False),
    sa.Column('upload_time', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_images_id'), 'images', ['id'], unique=False)
    op.create_table('image_features',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('image_id', sa.Integer(), nullable=False),
    sa.Column('brightness_mean', sa.Float(), nullable=False),
    sa.Column('brightness_std', sa.Float(), nullable=False),
    sa.Column('brightness_p5', sa.Float(), nullable=False),
    sa.Column('brightness_p50', sa.Float(), nullable=False),
    sa.Column('brightness_p95', sa.Float(), nullable=False),
    sa.Column('dynamic_range', sa.Float(), nullable=False),
    sa.Column('black_clip_ratio', sa.Float(), nullable=False),
    sa.Column('white_clip_ratio', sa.Float(), nullable=False),
    sa.Column('saturation_mean', sa.Float(), nullable=False),
    sa.Column('saturation_std', sa.Float(), nullable=False),
    sa.Column('mean_r', sa.Float(), nullable=False),
    sa.Column('mean_g', sa.Float(), nullable=False),
    sa.Column('mean_b', sa.Float(), nullable=False),
    sa.Column('lab_a_mean', sa.Float(), nullable=False),
    sa.Column('lab_b_mean', sa.Float(), nullable=False),
    sa.Column('dominant_colors', sa.JSON(), nullable=False),
    sa.Column('unique_colors_ratio', sa.Float(), nullable=False),
    sa.Column('sharpness', sa.Float(), nullable=False),
    sa.Column('edge_density', sa.Float(), nullable=False),
    sa.Column('entropy', sa.Float(), nullable=False),
    sa.Column('local_contrast', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['image_id'], ['images.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('image_id')
    )
    op.create_index(op.f('ix_image_features_id'), 'image_features', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_image_features_id'), table_name='image_features')
    op.drop_table('image_features')
    op.drop_index(op.f('ix_images_id'), table_name='images')
    op.drop_table('images')
    # ### end Alembic commands ###
